name: Build Android AAB

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build AAB
        run: |
          docker run --rm \
            -v "$PWD":/home/user/hostcwd \
            kivy/buildozer:latest \
            android debug

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: TodoApp-AAB
          path: bin/*.aab
